---
title: "Visualisation of Air Monitor Data"
author: "Wolfgang Huber"
format: 
  html:
    page-layout: full
---

Load the data file from the QingPing Air Monitor

```{r}
#| label: load1
#| message: FALSE
# files = c("2023-01-09--02-09.xlsx", "2023-01-09--03-19.xlsx", "The historical data of Qingping Air Monitor.xlsx")
files = c("The\ historical\ data\ of\ Endemannstr12\ 20240930-20241224.xlsx")
xl = lapply(files, readxl::read_excel) 
xr = dplyr::bind_rows(xl) 
xr = xr[!duplicated(xr), ]

xr$Time = as.POSIXct(xr$Time, format = "%d/%m/%Y %H:%M")
xr
dplyr::last(xr$Time)
```

Add locations from manual notes

```{r}
#| label: load2
#| message: FALSE
locs = readr::read_csv("locations.csv")
xr$where = factor(NA, levels = sort(unique(locs$where)))
for (i in seq_len(nrow(locs))) {
  end = if (i < nrow(locs)) (locs$start[i+1]) else +Inf
  rg = (xr$Time >= locs$start[i]) & (xr$Time < end) 
  xr$where[rg] = locs$where[i]
}
```

<!-- Remove the first 8 hours since data may be unreliable -->

```{r}
#| eval: false
#|echo: false
xrf = dplyr::filter(xr, (xr$Time - xr$Time[1]) > as.difftime("8", format = "%H"))
```

Date range
```{r}
xrf = dplyr::filter(xr, Time >= as.POSIXct("2024-12-06", format = "%Y-%m-%d"),
                        Time <= as.POSIXct("2024-12-20", format = "%Y-%m-%d")) 
```

```{r}
#| label: pivot
library("tidyr")
x = pivot_longer(xrf, cols = !matches("Time|where"))
```

```{r}
#| label: plotall
#| fig-dim: !expr c(15, 11)
#| out-width: 100%
library("ggplot2")
ggplot(x, aes(x = Time, y = value, col = where)) + geom_point(size = 0.5) +
  facet_wrap( ~name, ncol = 1, scales = "free") +
  scale_x_datetime(breaks = "1 day", minor_breaks = "6 hours",
                   date_labels = "%e.%m.")
```

```{r}
#| label: plotall2
#| fig-dim: !expr c(15, 3)
#| out-width: 100%
dplyr::filter(x, name %in% c("PM2.5 (μg/m³)", "Humidity (%RH)")) |>
  ggplot(aes(x = Time, y = value, col = name)) + geom_point(size = 0.5) +
    scale_x_datetime(breaks = "1 day", minor_breaks = "6 hours",
                     date_labels = "%e.%m.")
```

Gibt es einen Tagesrhythmus?

```{r}
#| label: plotdaily
#| fig-dim: !expr c(6, 6)
#| out-width: 100%
#| message: FALSE
library("dplyr")
xs = separate(data = x, col = Time, into  = c('Date', 'Time'), sep = ' ') |>
   group_by(Time, name, where) |>
   summarise(avg = mean(value, trim = 0.1)) 
#stopifnot(nrow(xs) == 24*4*5*3)
xs$Time = as.POSIXct(xs$Time, format = "%H:%M")
filter(xs, where == "Bad7") |>
  ggplot(aes(x = Time, y = avg)) + geom_point(size = 0.5) +
  facet_wrap( ~name, ncol = 1, scales = "free") +
  scale_x_datetime(breaks = "2 hour", date_labels = "%H:%M")
```